package generation.generator_3_20_1;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gps.proto

public final class Gps {
  private Gps() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GpsParametersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GpsParameters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    java.util.List<GpsParameter>
        getGpsDataList();
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    GpsParameter getGpsData(int index);
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    int getGpsDataCount();
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    java.util.List<? extends GpsParameterOrBuilder>
        getGpsDataOrBuilderList();
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    GpsParameterOrBuilder getGpsDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GpsParameters}
   */
  public static final class GpsParameters extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GpsParameters)
      GpsParametersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GpsParameters.newBuilder() to construct.
    private GpsParameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsParameters() {
      gpsData_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GpsParameters();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GpsParameters(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gpsData_ = new java.util.ArrayList<GpsParameter>();
                mutable_bitField0_ |= 0x00000001;
              }
              gpsData_.add(
                  input.readMessage(GpsParameter.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gpsData_ = java.util.Collections.unmodifiableList(gpsData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Gps.internal_static_GpsParameters_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Gps.internal_static_GpsParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GpsParameters.class, Builder.class);
    }

    public static final int GPSDATA_FIELD_NUMBER = 1;
    private java.util.List<GpsParameter> gpsData_;
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    @Override
    public java.util.List<GpsParameter> getGpsDataList() {
      return gpsData_;
    }
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    @Override
    public java.util.List<? extends GpsParameterOrBuilder>
        getGpsDataOrBuilderList() {
      return gpsData_;
    }
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    @Override
    public int getGpsDataCount() {
      return gpsData_.size();
    }
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    @Override
    public GpsParameter getGpsData(int index) {
      return gpsData_.get(index);
    }
    /**
     * <code>repeated .GpsParameter gpsData = 1;</code>
     */
    @Override
    public GpsParameterOrBuilder getGpsDataOrBuilder(
        int index) {
      return gpsData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gpsData_.size(); i++) {
        output.writeMessage(1, gpsData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gpsData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gpsData_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GpsParameters)) {
        return super.equals(obj);
      }
      GpsParameters other = (GpsParameters) obj;

      if (!getGpsDataList()
          .equals(other.getGpsDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGpsDataCount() > 0) {
        hash = (37 * hash) + GPSDATA_FIELD_NUMBER;
        hash = (53 * hash) + getGpsDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GpsParameters parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameters parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsParameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsParameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GpsParameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsParameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsParameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GpsParameters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GpsParameters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GpsParameters)
        GpsParametersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Gps.internal_static_GpsParameters_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Gps.internal_static_GpsParameters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GpsParameters.class, Builder.class);
      }

      // Construct using Gps.GpsParameters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGpsDataFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (gpsDataBuilder_ == null) {
          gpsData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gpsDataBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Gps.internal_static_GpsParameters_descriptor;
      }

      @Override
      public GpsParameters getDefaultInstanceForType() {
        return GpsParameters.getDefaultInstance();
      }

      @Override
      public GpsParameters build() {
        GpsParameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GpsParameters buildPartial() {
        GpsParameters result = new GpsParameters(this);
        int from_bitField0_ = bitField0_;
        if (gpsDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gpsData_ = java.util.Collections.unmodifiableList(gpsData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gpsData_ = gpsData_;
        } else {
          result.gpsData_ = gpsDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GpsParameters) {
          return mergeFrom((GpsParameters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GpsParameters other) {
        if (other == GpsParameters.getDefaultInstance()) return this;
        if (gpsDataBuilder_ == null) {
          if (!other.gpsData_.isEmpty()) {
            if (gpsData_.isEmpty()) {
              gpsData_ = other.gpsData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGpsDataIsMutable();
              gpsData_.addAll(other.gpsData_);
            }
            onChanged();
          }
        } else {
          if (!other.gpsData_.isEmpty()) {
            if (gpsDataBuilder_.isEmpty()) {
              gpsDataBuilder_.dispose();
              gpsDataBuilder_ = null;
              gpsData_ = other.gpsData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gpsDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpsDataFieldBuilder() : null;
            } else {
              gpsDataBuilder_.addAllMessages(other.gpsData_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GpsParameters parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GpsParameters) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GpsParameter> gpsData_ =
        java.util.Collections.emptyList();
      private void ensureGpsDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gpsData_ = new java.util.ArrayList<GpsParameter>(gpsData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GpsParameter, GpsParameter.Builder, GpsParameterOrBuilder> gpsDataBuilder_;

      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public java.util.List<GpsParameter> getGpsDataList() {
        if (gpsDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gpsData_);
        } else {
          return gpsDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public int getGpsDataCount() {
        if (gpsDataBuilder_ == null) {
          return gpsData_.size();
        } else {
          return gpsDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public GpsParameter getGpsData(int index) {
        if (gpsDataBuilder_ == null) {
          return gpsData_.get(index);
        } else {
          return gpsDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder setGpsData(
          int index, GpsParameter value) {
        if (gpsDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsDataIsMutable();
          gpsData_.set(index, value);
          onChanged();
        } else {
          gpsDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder setGpsData(
          int index, GpsParameter.Builder builderForValue) {
        if (gpsDataBuilder_ == null) {
          ensureGpsDataIsMutable();
          gpsData_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpsDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder addGpsData(GpsParameter value) {
        if (gpsDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsDataIsMutable();
          gpsData_.add(value);
          onChanged();
        } else {
          gpsDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder addGpsData(
          int index, GpsParameter value) {
        if (gpsDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsDataIsMutable();
          gpsData_.add(index, value);
          onChanged();
        } else {
          gpsDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder addGpsData(
          GpsParameter.Builder builderForValue) {
        if (gpsDataBuilder_ == null) {
          ensureGpsDataIsMutable();
          gpsData_.add(builderForValue.build());
          onChanged();
        } else {
          gpsDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder addGpsData(
          int index, GpsParameter.Builder builderForValue) {
        if (gpsDataBuilder_ == null) {
          ensureGpsDataIsMutable();
          gpsData_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpsDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder addAllGpsData(
          Iterable<? extends GpsParameter> values) {
        if (gpsDataBuilder_ == null) {
          ensureGpsDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gpsData_);
          onChanged();
        } else {
          gpsDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder clearGpsData() {
        if (gpsDataBuilder_ == null) {
          gpsData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gpsDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public Builder removeGpsData(int index) {
        if (gpsDataBuilder_ == null) {
          ensureGpsDataIsMutable();
          gpsData_.remove(index);
          onChanged();
        } else {
          gpsDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public GpsParameter.Builder getGpsDataBuilder(
          int index) {
        return getGpsDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public GpsParameterOrBuilder getGpsDataOrBuilder(
          int index) {
        if (gpsDataBuilder_ == null) {
          return gpsData_.get(index);  } else {
          return gpsDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public java.util.List<? extends GpsParameterOrBuilder>
           getGpsDataOrBuilderList() {
        if (gpsDataBuilder_ != null) {
          return gpsDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gpsData_);
        }
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public GpsParameter.Builder addGpsDataBuilder() {
        return getGpsDataFieldBuilder().addBuilder(
            GpsParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public GpsParameter.Builder addGpsDataBuilder(
          int index) {
        return getGpsDataFieldBuilder().addBuilder(
            index, GpsParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .GpsParameter gpsData = 1;</code>
       */
      public java.util.List<GpsParameter.Builder>
           getGpsDataBuilderList() {
        return getGpsDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GpsParameter, GpsParameter.Builder, GpsParameterOrBuilder>
          getGpsDataFieldBuilder() {
        if (gpsDataBuilder_ == null) {
          gpsDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GpsParameter, GpsParameter.Builder, GpsParameterOrBuilder>(
                  gpsData_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gpsData_ = null;
        }
        return gpsDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GpsParameters)
    }

    // @@protoc_insertion_point(class_scope:GpsParameters)
    private static final GpsParameters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GpsParameters();
    }

    public static GpsParameters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GpsParameters>
        PARSER = new com.google.protobuf.AbstractParser<GpsParameters>() {
      @Override
      public GpsParameters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsParameters(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsParameters> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GpsParameters> getParserForType() {
      return PARSER;
    }

    @Override
    public GpsParameters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GpsParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GpsParameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 long = 1;</code>
     * @return The long.
     */
    int getLong();

    /**
     * <code>int32 lat = 2;</code>
     * @return The lat.
     */
    int getLat();

    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code GpsParameter}
   */
  public static final class GpsParameter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GpsParameter)
      GpsParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GpsParameter.newBuilder() to construct.
    private GpsParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsParameter() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GpsParameter();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GpsParameter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              long_ = input.readInt32();
              break;
            }
            case 16: {

              lat_ = input.readInt32();
              break;
            }
            case 24: {

              height_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Gps.internal_static_GpsParameter_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Gps.internal_static_GpsParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GpsParameter.class, Builder.class);
    }

    public static final int LONG_FIELD_NUMBER = 1;
    private int long_;
    /**
     * <code>int32 long = 1;</code>
     * @return The long.
     */
    @Override
    public int getLong() {
      return long_;
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private int lat_;
    /**
     * <code>int32 lat = 2;</code>
     * @return The lat.
     */
    @Override
    public int getLat() {
      return lat_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (long_ != 0) {
        output.writeInt32(1, long_);
      }
      if (lat_ != 0) {
        output.writeInt32(2, lat_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (long_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, long_);
      }
      if (lat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lat_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GpsParameter)) {
        return super.equals(obj);
      }
      GpsParameter other = (GpsParameter) obj;

      if (getLong()
          != other.getLong()) return false;
      if (getLat()
          != other.getLat()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LONG_FIELD_NUMBER;
      hash = (53 * hash) + getLong();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + getLat();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GpsParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GpsParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GpsParameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GpsParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GpsParameter)
        GpsParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Gps.internal_static_GpsParameter_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Gps.internal_static_GpsParameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GpsParameter.class, Builder.class);
      }

      // Construct using Gps.GpsParameter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        long_ = 0;

        lat_ = 0;

        height_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Gps.internal_static_GpsParameter_descriptor;
      }

      @Override
      public GpsParameter getDefaultInstanceForType() {
        return GpsParameter.getDefaultInstance();
      }

      @Override
      public GpsParameter build() {
        GpsParameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GpsParameter buildPartial() {
        GpsParameter result = new GpsParameter(this);
        result.long_ = long_;
        result.lat_ = lat_;
        result.height_ = height_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GpsParameter) {
          return mergeFrom((GpsParameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GpsParameter other) {
        if (other == GpsParameter.getDefaultInstance()) return this;
        if (other.getLong() != 0) {
          setLong(other.getLong());
        }
        if (other.getLat() != 0) {
          setLat(other.getLat());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GpsParameter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GpsParameter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int long_ ;
      /**
       * <code>int32 long = 1;</code>
       * @return The long.
       */
      @Override
      public int getLong() {
        return long_;
      }
      /**
       * <code>int32 long = 1;</code>
       * @param value The long to set.
       * @return This builder for chaining.
       */
      public Builder setLong(int value) {
        
        long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 long = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLong() {
        
        long_ = 0;
        onChanged();
        return this;
      }

      private int lat_ ;
      /**
       * <code>int32 lat = 2;</code>
       * @return The lat.
       */
      @Override
      public int getLat() {
        return lat_;
      }
      /**
       * <code>int32 lat = 2;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(int value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lat = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        
        lat_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GpsParameter)
    }

    // @@protoc_insertion_point(class_scope:GpsParameter)
    private static final GpsParameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GpsParameter();
    }

    public static GpsParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GpsParameter>
        PARSER = new com.google.protobuf.AbstractParser<GpsParameter>() {
      @Override
      public GpsParameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsParameter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsParameter> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GpsParameter> getParserForType() {
      return PARSER;
    }

    @Override
    public GpsParameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface onNotifyGpsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:onNotifyGps)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code onNotifyGps}
   */
  public static final class onNotifyGps extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:onNotifyGps)
      onNotifyGpsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use onNotifyGps.newBuilder() to construct.
    private onNotifyGps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private onNotifyGps() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new onNotifyGps();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private onNotifyGps(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Gps.internal_static_onNotifyGps_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Gps.internal_static_onNotifyGps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              onNotifyGps.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof onNotifyGps)) {
        return super.equals(obj);
      }
      onNotifyGps other = (onNotifyGps) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static onNotifyGps parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static onNotifyGps parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static onNotifyGps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static onNotifyGps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static onNotifyGps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static onNotifyGps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static onNotifyGps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static onNotifyGps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static onNotifyGps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static onNotifyGps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static onNotifyGps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static onNotifyGps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(onNotifyGps prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code onNotifyGps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:onNotifyGps)
        onNotifyGpsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Gps.internal_static_onNotifyGps_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Gps.internal_static_onNotifyGps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                onNotifyGps.class, Builder.class);
      }

      // Construct using Gps.onNotifyGps.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Gps.internal_static_onNotifyGps_descriptor;
      }

      @Override
      public onNotifyGps getDefaultInstanceForType() {
        return onNotifyGps.getDefaultInstance();
      }

      @Override
      public onNotifyGps build() {
        onNotifyGps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public onNotifyGps buildPartial() {
        onNotifyGps result = new onNotifyGps(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof onNotifyGps) {
          return mergeFrom((onNotifyGps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(onNotifyGps other) {
        if (other == onNotifyGps.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        onNotifyGps parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (onNotifyGps) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:onNotifyGps)
    }

    // @@protoc_insertion_point(class_scope:onNotifyGps)
    private static final onNotifyGps DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new onNotifyGps();
    }

    public static onNotifyGps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<onNotifyGps>
        PARSER = new com.google.protobuf.AbstractParser<onNotifyGps>() {
      @Override
      public onNotifyGps parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new onNotifyGps(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<onNotifyGps> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<onNotifyGps> getParserForType() {
      return PARSER;
    }

    @Override
    public onNotifyGps getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GpsParameters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GpsParameters_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GpsParameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GpsParameter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onNotifyGps_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onNotifyGps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tGps.proto\"/\n\rGpsParameters\022\036\n\007gpsData\030" +
      "\001 \003(\0132\r.GpsParameter\"9\n\014GpsParameter\022\014\n\004" +
      "long\030\001 \001(\005\022\013\n\003lat\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\"" +
      "\r\n\013onNotifyGpsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GpsParameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GpsParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GpsParameters_descriptor,
        new String[] { "GpsData", });
    internal_static_GpsParameter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GpsParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GpsParameter_descriptor,
        new String[] { "Long", "Lat", "Height", });
    internal_static_onNotifyGps_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_onNotifyGps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onNotifyGps_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
